## This file is for local development only. It is not used in production. it is used to start the services locally.

services:
  postgres:
    image: postgres:alpine3.17
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./appdata/postgres:/var/lib/postgresql/data
  

  mattermost:
    image: mattermost/mattermost-team-edition
    container_name: mattermost
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      - MM_SQLSETTINGS_DATASOURCE=postgres://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable&connect_timeout=10
    
    ports:
      - 8065:8065
    volumes:
      - ./appdata/mattermost-data:/mattermost/data

