## This file is for local development only. It is not used in production. it is used to start the services locally.

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: teamrocket
      POSTGRES_USER: teamrocket
      POSTGRES_DB: mattermost
    ports:
      - 5432:5432
    volumes:
      - ./appdata/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - ./appdata/pgadmin:/var/lib/pgadmin
    

