name: Deploy Mattermost to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write # Allow CI to write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ortega-gallez-mattermost
          image: mattermost/mattermost-team-edition:latest
          region: us-central1
          flags: --port=8065
          env_vars: |
            MM_SQLSETTINGS_DATASOURCE=postgres://gallez_ortega:gallez_ortega@35.239.186.51:5432/?sslmode=disable&connect_timeout=10
